//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WalletAPI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shop_Shipping_address
    {
        public int tr_id { get; set; }
        public string retailer_id { get; set; }
        public string retailer_mobile { get; set; }
        public string reciver_name { get; set; }
        public string ship_address { get; set; }
        public string city { get; set; }
        public string pincode { get; set; }
        public string ship_mobile { get; set; }
        public string email_id { get; set; }
        public string landline_number { get; set; }
        public Nullable<System.DateTime> tr_date { get; set; }
    }
}
